import { sidebar } from "vuepress-theme-hope";

// 精选图标：https://vuepress-theme-hope.github.io/v2/zh/guide/interface/icon.html#iconfont-%E7%B2%BE%E9%80%89%E5%9B%BE%E6%A0%87
export default sidebar([
  "/DailyRoutine",
  "/Fitness",
  "/Read",
  {
    text: "数据分析（python）",
    icon: "chart_with_upwards_trend",
    prefix: "/数据分析/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "XlsxWriter",
    icon: "chart_with_upwards_trend",
    prefix: "/XlsxWriter/",
    link: "",
    collapsable: true,
    children: [
      {
        text: "快速开始",
        icon: "",
        prefix: "快速开始/",
        collapsable: true,
        children: "structure",
      },
      {
        text: "API使用详解",
        icon: "",
        prefix: "API使用详解/",
        collapsable: true,
        children: "structure",
      },
    ],
  },
  {
    text: "代码",
    icon: "rocket",
    prefix: "/code/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "移动通信",
    icon: "signal_strength",
    prefix: "/mobile/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🧰 软件应用",
    icon: "",
    prefix: "/apps/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🌐 页面开发",
    icon: "",
    prefix: "/web/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🏗️ 网站部署",
    icon: "",
    prefix: "/deploy/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🐋 Linux 服务",
    icon: "",
    prefix: "/services/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🪟 系统问题",
    icon: "",
    prefix: "/windows/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "🛖 生活",
    icon: "",
    prefix: "/family/",
    link: "",
    collapsable: true,
    children: "structure",
  },
  {
    text: "博客文章",
    icon: "blog",
    prefix: "/_posts/",
    link: "/blog",
    collapsable: true,
    children: "structure",
  },
]);
